<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>

		<TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
		<TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>

		<RootNamespace>Moedix.WinUI</RootNamespace>
		<ApplicationManifest>app.manifest</ApplicationManifest>

		<Platforms>x86;x64;ARM64</Platforms>

		<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>

		<PublishProfile>win10-$(Platform).pubxml</PublishProfile>

		<UseWinUI>true</UseWinUI>
		<UseMaui>true</UseMaui>

		<EnableDefaultMauiItems>false</EnableDefaultMauiItems>

		<PackageCertificateThumbprint>A3E383F476E861B04FCC0E864C98C3F527624905</PackageCertificateThumbprint>
		<AppxPackageSigningEnabled>true</AppxPackageSigningEnabled>

		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<DefaultLanguage>pt-BR</DefaultLanguage>

		<PublishReadyToRun>false</PublishReadyToRun>

		<PublishTrimmed>false</PublishTrimmed>
		<GenerateAppInstallerFile>True</GenerateAppInstallerFile>
		<AppxPackageSigningTimestampDigestAlgorithm>SHA256</AppxPackageSigningTimestampDigestAlgorithm>
		<AppxAutoIncrementPackageRevision>False</AppxAutoIncrementPackageRevision>
		<AppxSymbolPackageEnabled>False</AppxSymbolPackageEnabled>
		<GenerateTestArtifacts>True</GenerateTestArtifacts>
		<AppxBundle>Never</AppxBundle>
		<AppInstallerUri>D:\Moedix\</AppInstallerUri>
		<HoursBetweenUpdateChecks>0</HoursBetweenUpdateChecks>


	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="$(MauiVersion)" />
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="8.0.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Moedix\Moedix.csproj" />
		<MauiImage Include="Resources\Images\**\*.png" />
	</ItemGroup>

	<ItemGroup>
	  <Content Remove="Assets\logo.png.scale-125.png" />
	  <Content Remove="Assets\logo.png.scale-150.png" />
	  <Content Remove="Assets\logo.png.scale-200.png" />
	  <Content Remove="Assets\logo.png.scale-400.png" />
	  <Content Remove="Assets\logo100.png" />
	</ItemGroup>

	<ItemGroup>
	  <None Remove="Assets\logo.scale-100.png" />
	  <None Remove="Assets\logo.scale-150.png" />
	  <None Remove="Assets\logo.scale-200.png" />
	  <None Remove="logo25.ico" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="Assets\Images\*" TargetPath="%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<Manifest Include="$(ApplicationManifest)" />
	</ItemGroup>

	<ItemGroup Condition="'$(DisableMsixProjectCapabilityAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
		<ProjectCapability Include="Msix" />
	</ItemGroup>

	<ItemGroup>
	  <MauiIcon Include="Assets\logo100.png" />
	  <MauiImage Include="logo25.ico" />
	</ItemGroup>

	<PropertyGroup Condition="'$(DisableHasPackageAndPublishMenuAddedByProject)'!='true' and '$(EnableMsixTooling)'=='true'">
		<HasPackageAndPublishMenu>true</HasPackageAndPublishMenu>
	</PropertyGroup>

</Project>